# Copy this file to secrets.yml after creating a CompreFace recognition service.
# CompreFace UI: http://localhost:8001
# Double Take UI: http://localhost:3030
compreface_key: paste_compreface_recognition_api_key_here
