"""
research-bridge — Freya Research Agent glue layer

Multi-query research pipeline:
1. ChromaDB pulls N diverse dork techniques for the topic
2. Each technique becomes a targeted LDR search (site:X, filetype:Y, etc.)
3. Raw query added as final broad search
4. All results merged into one comprehensive PDF
5. Email delivered + HA webhook fired
"""

import os
import re
import time
import logging
import smtplib
import requests
import markdown
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from fastapi import FastAPI, BackgroundTasks
from pydantic import BaseModel
from weasyprint import HTML
from bs4 import BeautifulSoup

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("research-bridge")

app = FastAPI()

# ── Environment ───────────────────────────────────────────────────────────────
LDR_URL         = os.getenv("LDR_URL",          "http://local-deep-research:5000")
LDR_USER        = os.getenv("LDR_USERNAME",      "admin")
LDR_PASS        = os.getenv("LDR_PASSWORD",      "freyaresearch2026")
HA_URL          = os.getenv("HA_URL",            "http://homeassistant:8123")
HA_TOKEN        = os.getenv("HA_TOKEN",          "")
WEBHOOK_ID      = os.getenv("HA_WEBHOOK_ID",     "research_report_done")
REPORT_DIR      = "/app/reports"
GMAIL_USER      = os.getenv("GMAIL_USER",        "tomie.pearson@gmail.com")
GMAIL_PASS      = os.getenv("GMAIL_APP_PASS",    "")
GMAIL_TO        = os.getenv("GMAIL_TO",          "tomie.pearson@gmail.com")
CHROMADB_URL    = os.getenv("CHROMADB_URL",      "http://chromadb:8000")
OLLAMA_URL      = os.getenv("OLLAMA_URL",        "http://ollama:11434")
EMBED_MODEL     = os.getenv("EMBED_MODEL",       "nomic-embed-text")
CHROMA_BASE     = f"{CHROMADB_URL}/api/v2/tenants/default_tenant/databases/default_database"
DORK_COLLECTION = "google_dorking_knowledge"

# How many dorked queries to run per report (plus 1 raw query always added)
QUERY_BRANCHES  = int(os.getenv("QUERY_BRANCHES", "2"))
# Iterations per LDR job — keep low since we run multiple jobs
LDR_ITERATIONS  = int(os.getenv("LDR_ITERATIONS", "2"))

# ── CSS / HTML template ───────────────────────────────────────────────────────
PDF_CSS = """
body {
  font-family: 'DejaVu Sans', sans-serif;
  margin: 48px 56px;
  line-height: 1.65;
  color: #1a1a1a;
  font-size: 13px;
}
h1 { font-size: 22px; color: #0a0a0a; margin-bottom: 4px; }
h2 { font-size: 17px; color: #111; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-top: 28px; }
h3 { font-size: 14px; color: #222; margin-top: 20px; }
a  { color: #1a4fd4; }
code { background: #f0f0f0; padding: 1px 5px; border-radius: 3px; font-size: 12px; }
pre  { background: #f5f5f5; padding: 14px; border-radius: 4px; overflow-x: auto; font-size: 11px; }
blockquote { border-left: 4px solid #ccc; margin-left: 0; padding-left: 14px; color: #555; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; }
th, td { border: 1px solid #ccc; padding: 7px 10px; text-align: left; }
th { background: #f0f0f0; font-weight: bold; }
.report-meta { color: #666; font-size: 11px; margin-bottom: 24px; }
.section-divider { border: none; border-top: 2px solid #ddd; margin: 32px 0; }
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>{css}</style>
</head>
<body>
  <p class="report-meta">Generated by Freya Research Agent &bull; {timestamp} &bull; {num_searches} search strategies</p>
  {body}
</body>
</html>"""


class ResearchRequest(BaseModel):
    query: str
    title: str | None = None
    iterations: int = 3


# ── ChromaDB / Embeddings ─────────────────────────────────────────────────────

def get_embedding(text: str) -> list | None:
    """Get nomic-embed-text embedding from Ollama."""
    try:
        resp = requests.post(
            f"{OLLAMA_URL}/api/embeddings",
            json={"model": EMBED_MODEL, "prompt": text},
            timeout=30,
        )
        return resp.json().get("embedding")
    except Exception as e:
        log.warning("Embedding failed: %s", e)
        return None


def get_dork_collection_id() -> str | None:
    """Look up the google_dorking_knowledge collection ID."""
    try:
        resp = requests.get(f"{CHROMA_BASE}/collections", timeout=10)
        for col in resp.json():
            if col.get("name") == DORK_COLLECTION:
                return col.get("id")
        log.warning("Collection '%s' not found", DORK_COLLECTION)
        return None
    except Exception as e:
        log.warning("ChromaDB collection lookup failed: %s", e)
        return None


def retrieve_dork_techniques(query: str, n: int = 5) -> list[str]:
    """Query ChromaDB for relevant Google dorking techniques."""
    embedding = get_embedding(query)
    if not embedding:
        return []
    collection_id = get_dork_collection_id()
    if not collection_id:
        return []
    try:
        resp = requests.post(
            f"{CHROMA_BASE}/collections/{collection_id}/query",
            json={"query_embeddings": [embedding], "n_results": n, "include": ["documents"]},
            timeout=15,
        )
        docs = resp.json().get("documents", [[]])[0]
        log.info("Retrieved %d dork techniques from ChromaDB", len(docs))
        return docs
    except Exception as e:
        log.warning("ChromaDB query failed: %s", e)
        return []


# ── Query Set Builder ─────────────────────────────────────────────────────────

def build_query_set(raw_query: str, n_branches: int = 2) -> list[tuple[str, str]]:
    """
    Build a diverse set of (label, query) tuples.
    Each dork technique becomes one targeted search — one operator max.
    Raw query always added last for broad coverage.
    Returns: [(label, query), ...]
    """
    log.info("Building query set for: %r", raw_query)
    techniques = retrieve_dork_techniques(raw_query, n=n_branches + 3)
    valid_prefixes = ("site:", "filetype:", "intitle:", "inurl:")
    queries = []
    seen_operators = set()

    for technique in techniques:
        if len(queries) >= n_branches:
            break
        operator = technique.split("—")[0].strip()
        if (any(operator.startswith(p) for p in valid_prefixes)
                and len(operator) < 40
                and operator not in seen_operators):
            # Build friendly label from operator
            label = operator.replace("site:", "").replace("filetype:", "").replace("intitle:", "").replace("inurl:", "").split(".")[0].strip()
            queries.append((f"{label} search", f"{operator} {raw_query}"))
            seen_operators.add(operator)
            log.info("Branch %d: %r", len(queries), f"{operator} {raw_query}")

    # Always add raw query for broad coverage
    queries.append(("broad search", raw_query))
    log.info("Query set: %d branches total", len(queries))
    return queries


# ── LDR Job Runner ────────────────────────────────────────────────────────────

def run_ldr_job(session: requests.Session, query: str, iterations: int, label: str) -> str | None:
    """
    Run a single LDR research job and return the markdown report.
    Returns None on failure.
    """
    log.info("LDR job [%s]: %r (iterations=%d)", label, query, iterations)

    # Get fresh CSRF token
    try:
        csrf_resp = session.get(f"{LDR_URL}/auth/csrf-token", timeout=10)
        csrf_token = csrf_resp.json().get("csrf_token", "")
    except Exception as e:
        log.error("[%s] CSRF token failed: %s", label, e)
        return None

    headers = {"X-CSRF-Token": csrf_token}

    # Start job
    try:
        start_resp = session.post(
            f"{LDR_URL}/api/start_research",
            json={"query": query, "iterations": iterations},
            headers=headers,
            timeout=30,
        )
        research_id = start_resp.json().get("research_id")
        if not research_id:
            log.error("[%s] No research_id returned", label)
            return None
        log.info("[%s] research_id: %s", label, research_id)
    except Exception as e:
        log.error("[%s] Start failed: %s", label, e)
        return None

    # Poll for completion
    for attempt in range(120):
        time.sleep(5)
        try:
            status_resp = session.get(
                f"{LDR_URL}/api/research/{research_id}/status", timeout=15)
            status = status_resp.json().get("status", "unknown")
            progress = status_resp.json().get("progress", "")
            log.info("[%s][%d/120] status=%s progress=%s", label, attempt + 1, status, progress)
            if status == "completed":
                break
            if status == "failed":
                log.error("[%s] Research failed", label)
                return None
        except Exception as e:
            log.warning("[%s] Poll error: %s", label, e)
    else:
        log.error("[%s] Timed out", label)
        return None

    # Fetch report
    try:
        report_resp = session.get(f"{LDR_URL}/api/report/{research_id}", timeout=30)
        report_data = report_resp.json()
        report_md = report_data.get("summary") or report_data.get("report") or ""
        if not report_md or "could not produce results" in report_md.lower():
            log.warning("[%s] Empty or failed report", label)
            return None
        log.info("[%s] Report fetched (%d chars)", label, len(report_md))
        return report_md
    except Exception as e:
        log.error("[%s] Fetch failed: %s", label, e)
        return None


# ── Email ─────────────────────────────────────────────────────────────────────

def send_email(title: str, pdf_path: str, ts_str: str, num_searches: int):
    """Send completed report PDF to Tomie via Gmail SMTP."""
    if not GMAIL_PASS:
        log.warning("GMAIL_APP_PASS not set — skipping email")
        return
    try:
        msg = MIMEMultipart()
        msg["From"]    = GMAIL_USER
        msg["To"]      = GMAIL_TO
        msg["Subject"] = f"📄 Freya Report: {title}"

        body = f"""Your research report is ready.

Topic: {title}
Generated: {ts_str}
Search strategies used: {num_searches}

The PDF is attached and also available on your dashboard at:
http://192.168.68.51:8123/local/reports/

— Freya
"""
        msg.attach(MIMEText(body, "plain"))

        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        filename = os.path.basename(pdf_path)
        part.add_header("Content-Disposition", f"attachment; filename={filename}")
        msg.attach(part)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_PASS)
            server.sendmail(GMAIL_USER, GMAIL_TO, msg.as_string())

        log.info("Email sent to %s: %s", GMAIL_TO, filename)
    except Exception as e:
        log.error("Email send failed: %s", e)


# ── Helpers ───────────────────────────────────────────────────────────────────

def safe_filename(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_")[:60]


def ldr_session() -> requests.Session:
    """Authenticate with LDR and return a cookie session."""
    session = requests.Session()
    try:
        login_page = session.get(f"{LDR_URL}/auth/login", timeout=15)
        soup = BeautifulSoup(login_page.text, "html.parser")
        csrf_input = soup.find("input", {"name": "csrf_token"})
        csrf = csrf_input.get("value") if csrf_input else None
        session.post(f"{LDR_URL}/auth/login", data={
            "username": LDR_USER,
            "password": LDR_PASS,
            "csrf_token": csrf,
        }, timeout=15)
    except Exception as e:
        log.error("LDR auth error: %s", e)
    return session


def notify_ha(title: str, pdf_path: str | None, error: bool = False):
    """POST to the HA webhook."""
    if not HA_TOKEN:
        log.warning("HA_TOKEN not set — skipping webhook")
        return
    payload = {"title": title, "pdf_path": pdf_path, "error": error}
    try:
        requests.post(
            f"{HA_URL}/api/webhook/{WEBHOOK_ID}",
            json=payload,
            headers={"Authorization": f"Bearer {HA_TOKEN}"},
            timeout=10,
        )
        log.info("HA webhook fired: %s", payload)
    except Exception as e:
        log.error("HA webhook error: %s", e)


# ── Main Research Task ────────────────────────────────────────────────────────

def run_research(query: str, title: str, iterations: int):
    """
    Multi-query research pipeline:
    1. Build diverse query set using ChromaDB dork techniques
    2. Run each query as a separate LDR job
    3. Merge all successful reports into one document
    4. Convert to PDF, email, fire HA webhook

    iterations parameter controls depth:
      1 = quick:    2 branches x 1 iteration
      2 = standard: 2 branches x 2 iterations  (default)
      3 = standard: 3 branches x 2 iterations
      5 = deep:     4 branches x 3 iterations
    """
    log.info("Starting multi-query research: %r (requested iterations=%d)", query, iterations)

    # Derive branches and LDR iterations from requested depth
    if iterations <= 1:
        n_branches   = 2
        ldr_iters    = 1
        depth_label  = "quick"
    elif iterations <= 2:
        n_branches   = 2
        ldr_iters    = 2
        depth_label  = "standard"
    elif iterations <= 3:
        n_branches   = 3
        ldr_iters    = 2
        depth_label  = "thorough"
    else:
        n_branches   = 4
        ldr_iters    = 3
        depth_label  = "deep"

    log.info("Depth: %s — %d branches x %d iterations each", depth_label, n_branches, ldr_iters)

    # Build query set
    query_set = build_query_set(query, n_branches=n_branches)
    session = ldr_session()

    # Run each query branch sequentially
    sections = []
    successful = 0
    for label, q in query_set:
        result = run_ldr_job(session, q, ldr_iters, label)
        if result:
            sections.append((label, q, result))
            successful += 1
        else:
            log.warning("Branch [%s] returned no results — skipping", label)

    if not sections:
        log.error("All research branches failed — no content to report")
        notify_ha(title, None, error=True)
        return

    log.info("%d/%d branches produced results", successful, len(query_set))

    # Merge all sections into one markdown document
    merged_md = f"# {title}\n\n"
    merged_md += f"*Freya Research Report — {successful} search strategies used*\n\n"

    for i, (label, q, content) in enumerate(sections):
        merged_md += f"\n\n---\n\n## Section {i+1}: {label.title()}\n"
        merged_md += f"*Search query: `{q}`*\n\n"
        merged_md += content

    # File names
    base     = safe_filename(title)
    ts       = int(time.time())
    pdf_name = f"{base}_{ts}.pdf"
    md_name  = f"{base}_{ts}.md"
    ts_str   = time.strftime("%Y-%m-%d %H:%M", time.localtime(ts))

    os.makedirs(REPORT_DIR, exist_ok=True)

    # Save markdown
    with open(f"{REPORT_DIR}/{md_name}", "w", encoding="utf-8") as f:
        f.write(merged_md)
    log.info("Markdown saved: %s", md_name)

    # Convert to PDF
    pdf_full_path = f"{REPORT_DIR}/{pdf_name}"
    try:
        html_body = markdown.markdown(
            merged_md,
            extensions=["tables", "fenced_code", "toc"]
        )
        html_str = HTML_TEMPLATE.format(
            css=PDF_CSS,
            timestamp=ts_str,
            num_searches=successful,
            body=html_body,
        )
        HTML(string=html_str).write_pdf(pdf_full_path)
        log.info("PDF saved: %s", pdf_name)
    except Exception as e:
        log.error("PDF generation failed: %s", e)
        notify_ha(title, f"/local/reports/{md_name}", error=False)
        return

    # Email and notify
    send_email(title, pdf_full_path, ts_str, successful)
    notify_ha(title, f"/local/reports/{pdf_name}", error=False)
    log.info("Done: %s", pdf_name)


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    ldr_ok = False
    try:
        r = requests.get(f"{LDR_URL}/auth/login", timeout=5)
        ldr_ok = r.status_code < 500
    except Exception:
        pass
    return {"status": "ok", "ldr_reachable": ldr_ok, "ldr_url": LDR_URL, "ha_url": HA_URL}


@app.post("/research")
def research(req: ResearchRequest, background_tasks: BackgroundTasks):
    title = req.title or req.query
    log.info("Research request: query=%r title=%r iterations=%d", req.query, title, req.iterations)
    background_tasks.add_task(run_research, req.query, title, req.iterations)
    return {
        "status": "started",
        "query": req.query,
        "title": title,
        "iterations": req.iterations,
        "message": "Research started. HA webhook will fire when complete.",
    }


@app.get("/reports")
def list_reports():
    try:
        files = sorted(os.listdir(REPORT_DIR), reverse=True)
        return {"reports": files}
    except Exception:
        return {"reports": []}
