- id: '1774333903458'
  name: Party Time
  entities:
    light.ceilingfanlight:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      color_temp_kelvin:
      hs_color:
      - 360
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      icon: mdi:ceiling-fan-light
      friendly_name: Ceiling Fan Light
      supported_features: 0
      state: 'on'
    light.counterlamp1:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      color_temp_kelvin:
      hs_color:
      - 36
      - 100
      rgb_color:
      - 255
      - 153
      - 0
      xy_color:
      - 0.579
      - 0.403
      icon: mdi:lamp
      friendly_name: Left Lamp
      supported_features: 0
      state: 'on'
    light.counterlamp2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      color_temp_kelvin:
      hs_color:
      - 298
      - 100
      rgb_color:
      - 247
      - 0
      - 255
      xy_color:
      - 0.375
      - 0.15
      icon: mdi:lamp
      friendly_name: Right Lamp
      supported_features: 0
      state: 'on'
    light.biglamp_one:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      color_temp_kelvin:
      hs_color:
      - 118
      - 85
      rgb_color:
      - 45
      - 255
      - 38
      xy_color:
      - 0.185
      - 0.718
      friendly_name: BigLamp one
      supported_features: 0
      state: 'on'
    light.biglamp_two:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 255
      color_temp_kelvin:
      hs_color:
      - 230
      - 95
      rgb_color:
      - 13
      - 53
      - 255
      xy_color:
      - 0.138
      - 0.059
      icon: mdi:lamp
      friendly_name: Big Lamp Two
      supported_features: 0
      state: 'on'
  icon: mdi:party-popper
  metadata:
    light.biglamp_one:
      entity_only: true
    light.biglamp_two:
      entity_only: true
